before_cache:
  - find "${HOME}"/.ivy2/cache -name "ivydata-*.properties" -print -delete
cache:
  directories:
    - ${HOME}/.ivy2/cache

env:
  - runner_image="constellationapplication/netbeans-runner:8.2"

# Disable shallow clone for SCM SonarCloud analysis
git:
  depth: false

jobs:
  include:

  - stage: Run Tests
    dist: trusty
    language: java
    services:
      - docker
    script:
      - docker pull "${runner_image}"
      - docker run -v "${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}" -v "${HOME}"/.ivy2/cache:/root/.ivy2/cache --workdir "${TRAVIS_BUILD_DIR}" "${runner_image}" .travis/run-tests.sh
      - .travis/sonar.sh
    addons:
      sonarcloud:
        organization: "constellation-app"
        token: $SONAR_TOKEN

  - stage: Build zip
    dist: trusty
    language: generic
    services:
      - docker
    script:
      - docker pull "${runner_image}"
      - docker run -v "${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}" -v "${HOME}"/.ivy2/cache:/root/.ivy2/cache --workdir "${TRAVIS_BUILD_DIR}" "${runner_image}" .travis/build-zip.sh

    deploy:
      provider: releases
      token:
        secure: "t1B8602NeQHFkarp5zn5xfRpN9Oxa+h7o+F2Z1IADGWvniBfDGxqs+Fyc+YKWhsrKsFq8MOhbwcPo+u10ces/1aDl2YoYgHn8GENU206GPM73fadIUFA8O8segz6Hzwvm4pp2SjiJUxalHlZVt2JaoK141a1/GPBem51Y54+VMhnFXuUmzxpZd1rkrwCXQE0BFJjCrIWdkq+NtYiw9EZ7ZKGwPoewF7qymoqOaMQOPLu3bgYydYKZFyT4H7dgr7IVxWJdDPd0wNwveMXaLN+0JlikkmVOPH2PSdVKnJsZv7XZE80p8XbB79lTsHDhZTWfyKzUgrgePebgu785wZGqjX7JVilcfZuIkNtd1q0s49l7C0GL+rvnZrAqxI2geBKpk7TMFtGqxqSKFxZ0eLCxfWIBoPkS3RY9xexQGAxjDcgvTbS1eBq5H4XGZ9/nUjKJpOJBbYsdeBpnHJ+5PDhyQewp0+4MtvHU9K4i113Zd/VbXTuCuBcCTk4HMnP8pPTzuqaW1fNLMmfu9iZ10n+j+ZVi5lC9gxl4sQP7uhWjhFOU3Uzz6+DOphnq5gyle9A6sK/GUmlLL1Tji+cgrTQ379G2KhkLP/AQrOfmzr4kV0wHjjCwf5ZHKngIW6lF77alEtW2pEWVvy+s7gLostFUmhZCOLgjOVYrQ+ntABqN3A=" 
      file: 'dist/constellation.zip'
      draft: true
      on:
        repo: constellation-app/constellation
        branch: feature/test-deployment
