before_cache:
  - find "${HOME}"/.ivy2/cache -name "ivydata-*.properties" -print -delete
cache:
  directories:
    - ${HOME}/.ivy2/cache

env:
  - runner_image="constellationapplication/netbeans-runner:8.2"

# Disable shallow clone for SCM SonarCloud analysis
git:
  depth: false

jobs:
  include:

  - stage: Run Tests
    dist: trusty
    language: java
    services:
      - docker
    script:
      - docker pull "${runner_image}"
      - docker run -v "${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}" -v "${HOME}"/.ivy2/cache:/root/.ivy2/cache --workdir "${TRAVIS_BUILD_DIR}" "${runner_image}" .travis/run-tests.sh
      - .travis/sonar.sh
    addons:
      sonarcloud:
        organization: "constellation-app"
        token: $SONAR_TOKEN

  - stage: Build zip
    dist: trusty
    language: generic
    services:
      - docker
    script:
      - docker pull "${runner_image}"
      - docker run -v "${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}" -v "${HOME}"/.ivy2/cache:/root/.ivy2/cache --workdir "${TRAVIS_BUILD_DIR}" "${runner_image}" .travis/build-zip.sh

deploy:
  provider: releases
  token:
    secure: "g/IagxpDZe2R1ryygpwX5OvHNha2SjDCMPdnUINnj5UnF6M/yHMDOuiHlTfCqqYFSiDgwNm59BvB5qzv5DCcJ6rZEzOaI0mCbmC4CTsrDDoY18UaXKiq06Ktie65tfV9wrEd+kdU5Xhzri4FRPMgH5QGHu7g98lZozjyVqajP6pGR/5psPe2/m7WWrxwYHKsTR+ThZXJTYnqP1+JCv625UehvG6C1l6f99ztuclDGb6n0tHs2BHLvtDeKVw2xzAa2eo8r5K0uAq4E4JnNmBF0kvFOK066XBNFywUqc1qgFCPd4sxnn5abQ7F6ZqZxNOim0vxdkqQhhlSJTQFt0bhQg1qDr2h1J5th/LPeOikntS1s3+/x0brCDsaS/8OZtRzYJrF5FnUaA6raIr3srzv2rzb2rroQN5ETUtRzaShtGEG4voOZrzdmY5KYyyoncqu1DoSe/45lGdrACsQLQIRmTI/uZFiVpCMc7FbdGm4kGCu6CfAIRi5grCnh48//y1h78fBYiV2ZVfW73NcO4U9noF7FEv9c3dvAjPi7mpPUm8Iin3zIbI6KHjabiSEAtgjo5nYBo085sMvxSB+I5VNj+h0ZsmCr1RHJKlbnocNrZv+b1SyqUbm3FWqq6NAYwYwARQysxkS3uuSVwVuqaNsM4KVaSbnB+q2r0FjCqqv7hQ=" 
  file: 'dist/constellation.zip'
  on:
    repo: constellation-app/constellation
    branch: feature/test-deployment
