jobs:
  include:
  - stage: Run Tests
    language: java
    before_script:
    - unset -v _JAVA_OPTIONS
    - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
    env: JDK=zulu11.31.11-ca-fx-jdk11.0.3-linux_x64
    script: source install-jdk.sh --url https://cdn.azul.com/zulu/bin/zulu11.31.11-ca-fx-jdk11.0.3-linux_x64.tar.gz
    sudo: false
    dist: trusty
    script:
    - docker pull "$IMAGE_NAME" || true
    - docker run -v $(pwd):/workdir/ --workdir /workdir/ constellation-app/netbeans-builder .travis/script.sh
    - sonar-scanner
    services:
    - docker
    env: IMAGE_NAME=constellation-app/netbeans-builder
    addons:
        sonarcloud:
        organization: theden-github
        token:
          secure: oZIesK+gN7WK10wbwh6xi+4jn6SV+TogX+yIaNpfYbqxR0eEhlqcNsc0LsGz/ITdg9PbIu1m66Y8Wk5TUoOK6LLUjK/t8vSXK5i/FB2K8dilgal8YKFwat/r2uWIrIhgvA/eR6fSit5TqKMVqCJByLmSOfHXk87XHL3xxK/XyGEJAI3r89PoLSwAyVBlf1pW/bpQhz4Enuz6M13W+gCeQX1tpTpEq0HIKO2kjDBuinTlANr2wnh1PE5xX/GULkXyVv01Xeqom2SbnMS32vfXyrKh2KtDFuV4P/DPZHt3oo+cAulNUVxUf3/DcmuqHX8rnHX37xB4rSo5QtJF0iGIK4q4HGFWPIB4ih1a+UWIamR/n6hhx8PwkBugapNizN05D4yzmcPyYBeUxhAkP/+7eQ0VyAZY7o7lLPWA26jCi6/F41XC9OxMKqZpeSoNJRDsWX553tcBpcBiAuPVXQ5zgqVWnbCa4yVQyPZ4mE41Svn3k06HvUHExZyCBBMwT8vy5ULoUjchKOLVcJEXuNroIxV7TujKHnrLZ2s73r+JFZegIgIzVYap3OKiA7h915IIi9YtEytD6tSANbe1JHM1c6lq7xtHu5JZK9hwWxICZb9rP83f6Vt6iPjMH8bkK9kz6YhenWFl3+sXaWdDmulREH6Hk5ORblFm1U7nHlM5rY0=
    after_script:
    - echo JAVA_HOME = ${JAVA_HOME}
    - echo PATH = ${PATH}
    - ls ${JAVA_HOME}
    - java -version
  - stage: Build zip
    language: java
    before_script:
    - unset -v _JAVA_OPTIONS
    - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
    env: JDK=zulu11.31.11-ca-fx-jdk11.0.3-linux_x64
    script: source install-jdk.sh --url https://cdn.azul.com/zulu/bin/zulu11.31.11-ca-fx-jdk11.0.3-linux_x64.tar.gz
    sudo: false
    dist: trusty
    script:
    - docker pull "$IMAGE_NAME" || true
    - docker run -v $(pwd):/workdir/ --workdir /workdir/ constellation-app/netbeans-builder .travis/build-zip.sh
    dist: trusty
    sudo: required
    services:
    - docker
    env: IMAGE_NAME=constellation-app/netbeans-builder
    language: generic
after_script:
    - echo JAVA_HOME = ${JAVA_HOME}
    - echo PATH = ${PATH}
    - ls ${JAVA_HOME}
    - java -version
deploy:
  provider: releases
  api_key:
    secure: Kahmrg2n7tWFhJ7mcC+wPdCLdcyz4loQ0lfMur48ZQ08I7OTJxNz0XVkXgy/aF0VfNePKomRgc3FutWsn7KLDH5eFZL/Vu/giIJIFzK1R+b89Tv35lpHCnMall78YKt3oN9HWB30PktTE/MHXtulB/DjaJp6rKTpo2xlMK9rM+NFlOt/lwc1YHEgW+M59u+OAGJWuowL6Vp8O9n0y8rmw3Au4SoIPv3zYFXh6IVTxd7qMysmH+BX7Wn0STye8qGyb3JjM6H1VyKAtKI7yoMREhmKmt0Q218Y5+7QMtiQa/C2ACYCGQAZaKIhbK8ZYvvruY3EWCVpSI8VOd889NFf8OKd835v8ElmTkJiQEQ7K2GLTINuz9GKupY6SfLbcx5/rhGKm59WxMcTLFUtS7p4zg1X68AZI92usGe3XEe/L2wrGOQzewZEQzfS/mTLFHAkVfbrgh3QJM8kFttk+nYvnzzwN+cpOx7h01tUmcjrpE/qLqDe89yvnVkYdUHGPFAyWL9EiyNgx7+nSeJhNWbGsC86HlckARWV0S1JrJu3W5Ls3613IfDVlqCmNSQF6KDaZTdtKS0ELM/2qJVzmU+Fh9qqoODz+ZB7rS8FAMMk+5NvZr1p/wXDz96KNZpTbmm57Ry/KPaklzHHQ7rQt2Inxb6Ug3wd7Mq310kgCcY+blk=
  file: 'dist/constellation.zip'
  on:
    repo: constellation-app/constellation
    branch: master
    tags: true